[package]
name = "tarka-polars"
description = "Polars data frames, Parquet and Arrow IPC files as tarka input"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
oxrdf.workspace = true
polars = { workspace = true }
rayon.workspace = true
thiserror.workspace = true
tarka.workspace = true
tarka-core.workspace = true
tarka-io.workspace = true

[dev-dependencies]
chrono = "0.4"
oxrdfio.workspace = true
